AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lutils SAM app

Globals:
  Function:
    Timeout: 900

Resources:
  S3TextLinesToSNSLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_s3_text_lines_to_sns/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 10
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: "*"
      Environment:
        Variables:
          sns_arn: "arn:aws:sns:us-east-1:112280397275:lutil_s3_text_lines"
          region: !Sub "${AWS::Region}"
          accountid: !Sub "${AWS::AccountId}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProcessingBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key: 
                Rules:
                - Name: prefix
                  Value: lutil_s3_text_lines_to_sns

  S3FilenamesToSNSLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_s3_filenames_to_sns/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 10
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "s3:List*"
              Resource: !Sub "arn:aws:s3:::*"
            - Effect: Allow
              Action: "s3:List*"
              Resource: !Sub "arn:aws:s3:::*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: "*"
      Environment:
        Variables:
          sns_arn: "arn:aws:sns:us-east-1:112280397275:lutil_s3_text_lines"
          region: !Sub "${AWS::Region}"
          accountid: !Sub "${AWS::AccountId}"
##      Events:
##        S3Event:
##          Type: S3
##          Properties:
##            Bucket: !Ref ProcessingBucket
##            Events: s3:ObjectCreated:*
##            Filter: 
##              S3Key: 
##                Rules:
##                - Name: prefix
##                  Value: lutil_s3_text_lines_to_sns

  DownloadURLLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_download_url/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 25
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:*"
              Resource: "*"
      Environment:
        Variables:
          s3_bucket: !Ref ProcessingBucket
          use_guids_for_filenames: "no"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref DownloadURLSNS

  DownloadURLSeleniumLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Downloads a URL using Selenium
      CodeUri: lutil_download_url_selenium/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 25
      Layers: 
        - !Ref Shared
      MemorySize: 512  
      Environment: 
        Variables:
          PATH: /tmp/bin
          PYTHON_PATH: /opt/python
          s3_bucket: !Ref ProcessingBucket
          use_guids_for_filenames: "no"
      Tags:
        Type: "lutils"
        Environment: lutils
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:*"
              Resource: "*"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref DownloadURLSeleniumSNS

  FanHandlerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Inserts or deletes fan in records into the fan in table
      CodeUri: lutil_fan_handler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Tags:
        Type: "lutils"
        Environment: lutils
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanInProcessingTable
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanEventsTestSNS


  Shared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-simplified
      Description: Dependencies for Selenium and the headless browser
      ContentUri: 
        Bucket: !Sub  "lutils-pipeline-artifactsbucket-98fi0mj7zik2"
        Key: "python-selenium-simplified.zip"
      CompatibleRuntimes:
        - python3.7


  ProcessingBucket:
    Type: AWS::S3::Bucket    
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for processing files and storing output
    Properties:
      Tags:
      - Key: Name
        Value: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - processing

  S3FilenamesLSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_s3_filenames_output"
      TopicName: "lutil_s3_filenames_output"

  DownloadURLSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_s3_text_lines_output"
      TopicName: "lutil_s3_text_lines_output"

  DownloadURLSeleniumSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_s3_text_lines_output_selenium"
      TopicName: "lutil_s3_text_lines_output_selenium"

  FanEventsSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_fan_events"
      TopicName: "lutil_fan_events"

  FanEventsTestSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_fan_events_test"
      TopicName: "lutil_fan_events_test"

  FanProcessingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: process_and_item
        Type: String
      TableName: lutil-fan-processing

  FanProcessingTableTest:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: process_and_item
        Type: String
      TableName: lutil-fan-processing-test

  FanInHistory:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: process_and_item_and_date
        Type: String
      TableName: lutil_fan-in-history


Outputs:
  S3TextLinesToSNSLambda:
    Description: "S3TextLinesToSNSLambda Lambda Function ARN"
    Value: !GetAtt S3TextLinesToSNSLambda.Arn

  S3ProcessingBucket:
    Description: "S3ProcessingBucket ARN"
    Value: !GetAtt ProcessingBucket.Arn


