AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lutils SAM app

Globals:
  Function:
    Timeout: 900

Resources:
  S3TextLinesToSNSLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lutil_s3_text_lines_to_sns/
      Handler: app.lambda_handler
      Runtime: python3.7
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}-processing"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}-processing/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: "*"
      Environment:
        Variables:
          sns_arn: "arn:aws:sns:us-east-1:112280397275:lutil_s3_text_lines"
          region: !Sub "${AWS::Region}"
          accountid: !Sub "${AWS::AccountId}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProcessingBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key: 
                Rules:
                - Name: prefix
                  Value: lutil_s3_text_lines_to_sns

  DownloadURLLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_download_url/
      Handler: app.lambda_handler
      Runtime: python3.7
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}-processing"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}-processing/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:*"
              Resource: "*"
      Environment:
        Variables:
          s3_bucket: !Sub "${AWS::StackName}-processing"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref DownloadURLSNS

  ProcessingBucket:
    Type: AWS::S3::Bucket    
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for processing files and storing output
    Properties:
      BucketName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - processing

  DownloadURLSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "lutil_s3_text_lines_output"
      TopicName: "lutil_s3_text_lines_output"


Outputs:
  S3TextLinesToSNSLambda:
    Description: "S3TextLinesToSNSLambda Lambda Function ARN"
    Value: !GetAtt S3TextLinesToSNSLambda.Arn

  S3ProcessingBucket:
    Description: "S3ProcessingBucket ARN"
    Value: !GetAtt ProcessingBucket.Arn

