AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lutils SAM app

Globals:
  Function:
    Timeout: 900

Resources:
  ################################
  ### Lambdas
  ################################
  Shared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-simplified
      Description: Dependencies for Selenium and the headless browser
      ContentUri: 
        Bucket: !Sub  "lutils-pipeline-artifactsbucket-98fi0mj7zik2"
        Key: "python-selenium-simplified.zip"
      CompatibleRuntimes:
        - python3.7


  Common:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common
      Description: Custom python code shared across the app
      ContentUri: common_layer/
      CompatibleRuntimes:
        - python3.7

  CommonHex:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common
      Description: Custom python code shared across the app
      ContentUri: common_layer_hex/
      CompatibleRuntimes:
        - python3.7        




  S3TextLinesToSNSLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_s3_text_lines_to_sns/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 10
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: "*"
      Environment:
        Variables:
          sns_arn: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:lutil_s3_text_lines"
          region: !Sub "${AWS::Region}"
          accountid: !Sub "${AWS::AccountId}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProcessingBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key: 
                Rules:
                - Name: prefix
                  Value: lutil_s3_text_lines_to_sns


  S3FilenamesToSNSLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_s3_filenames_to_sns/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 10
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "s3:List*"
              Resource: !Sub "arn:aws:s3:::*"
            - Effect: Allow
              Action: "s3:List*"
              Resource: !Sub "arn:aws:s3:::*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: "*"
      Environment:
        Variables:
          sns_arn: "arn:aws:sns:us-east-1:112280397275:lutil_s3_text_lines"
          region: !Sub "${AWS::Region}"
          accountid: !Sub "${AWS::AccountId}"
##      Events:
##        S3Event:
##          Type: S3
##          Properties:
##            Bucket: !Ref ProcessingBucket
##            Events: s3:ObjectCreated:*
##            Filter: 
##              S3Key: 
##                Rules:
##                - Name: prefix
##                  Value: lutil_s3_text_lines_to_sns

  DownloadURLLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lutil_download_url/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 25
      Tags:
        Type: "lutils"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:*"
              Resource: "*"
      Environment:
        Variables:
          s3_bucket: !Ref ProcessingBucket
          use_guids_for_filenames: "no"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref DownloadURLSNS

  DownloadURLSeleniumLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Downloads a URL using Selenium
      CodeUri: lutil_download_url_selenium/
      Handler: app.lambda_handler
      Runtime: python3.7
      ReservedConcurrentExecutions: 25
      Layers: 
        - !Ref Shared
      MemorySize: 512  
      Environment: 
        Variables:
          PATH: /tmp/bin
          PYTHON_PATH: /opt/python
          s3_bucket: !Ref ProcessingBucket
          use_guids_for_filenames: "no"
      Tags:
        Type: "lutils"
        Environment: lutils
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*"
            - Effect: Allow
              Action: "*"
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}*/*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "sns:*"
              Resource: "*"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref DownloadURLSeleniumSNS


  FanHandlerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Responds to inserts or deletes fan in records into the fan in table
      CodeUri: lutil_fan_log_dbstream/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsSNS
          TABLE_NAME: AUDIT #!Ref FanProcessingPartTestTable
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingPartTestTable 
        - DynamoDBCrudPolicy:
            TableName: "AUDIT" 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:lutil_*"
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FanProcessingPartTestTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  FanDBStreamHandlerTestLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Responds to inserts or deletes fan in records into the fan in table
      CodeUri: lutil_fan_dbstream_handler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsTestSNS
          TABLE_NAME: !Ref FanProcessingPartTestTable
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingPartTestTable 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:${AWS::StackName}*"
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FanProcessingPartTestTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  FanStartProcessTestLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Initiate a fan out process for a set of tasks
      CodeUri: lutil_fan_start_process/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsSNS
          TABLE_NAME: !Ref FanProcessingPartTestTable 
          POWERTOOLS_METRICS_NAMESPACE: lutils
          POWERTOOLS_SERVICE_NAME: fan-logging
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref CommonHex
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingPartTestTable 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:${AWS::StackName}*"

  FanCompleteTaskTestLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Mark a fan out task as completed
      CodeUri: lutil_fan_complete_task/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsSNS
          TABLE_NAME: !Ref FanProcessingPartTestTable 
          POWERTOOLS_METRICS_NAMESPACE: lutils
          POWERTOOLS_SERVICE_NAME: fan-logging
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref CommonHex
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingPartTestTable 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:${AWS::StackName}*"



  #--------------------------------
  # e2e testing lambdas
  #--------------------------------
  FanTestE2EProducerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Sample fan client to receive test events
      CodeUri: lutil_fan_e2e_producer/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          START_PROCESS_LAMBDA_NAME: !Ref FanStartProcessTestLambda
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function/${AWS::StackName}*"


  FanTestE2EConsumerLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Sample fan client to receive test events
      CodeUri: lutil_fan_e2e_consumer/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsTestSNS
          TABLE_NAME: !Ref FanProcessingPartTestTable
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingPartTestTable 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:${AWS::StackName}*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - dynamodb:DescribeTable
              Resource: !Sub "arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/${AWS::StackName}*"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanEventsTestSNS
            FilterPolicy: # only accept specific message types
              event_name:
                - "task_created" 
              process_name:
                - "e2e tests" 


  FanTestE2ECompletedLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Sample fan client to receive test events
      CodeUri: lutil_fan_e2e_completed/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsSNS
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanProcessingTableTest 
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:lutil_*"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanEventsTestSNS


  FanLogEventsLambda:
    Type: AWS::Serverless::Function 
    Properties:
      Description: Log all fan events for debugging
      CodeUri: lutil_fan_log_events/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          HANDLER_SNS_TOPIC_ARN: !Ref FanEventsSNS
          POWERTOOLS_METRICS_NAMESPACE: lutils
          POWERTOOLS_SERVICE_NAME: fan-logging
      Tags:
        Type: "lutils"
        Environment: lutils
      Layers: 
        - !Ref Common
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ProcessingBucket
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - sns:Get*
                - sns:Publish*
              Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:lutil_*"
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanEventsSNS
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanEventsTestSNS





  ################################
  ### S3
  ################################
  ProcessingBucket:
    Type: AWS::S3::Bucket    
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for processing files and storing output
    Properties:
      Tags:
      - Key: Name
        Value: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - processing


  ################################
  ### SNS
  ################################
  S3FilenamesSNS:
    Type: AWS::SNS::Topic

  DownloadURLSNS:
    Type: AWS::SNS::Topic


  DownloadURLSeleniumSNS:
    Type: AWS::SNS::Topic


  FanEventsSNS:
    Type: AWS::SNS::Topic


  FanEventsTestSNS:
    Type: AWS::SNS::Topic



  ################################
  ### Tables
  ################################
  FanProcessingTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "process_id"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "pk"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: process_id
          KeySchema:
            - AttributeName: process_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: True


  FanProcessingTableTest:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "process_id"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "pk"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: process_id
          KeySchema:
            - AttributeName: process_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: True

  FanProcessingPartTestTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "sk"
          AttributeType: "S"
        - 
          AttributeName: "gs1_pk"
          AttributeType: "S"
        - 
          AttributeName: "gs1_sk"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "pk"
          KeyType: "HASH"
        -
          AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: gs1
          KeySchema:
            - AttributeName: gs1_pk
              KeyType: HASH
            - AttributeName: gs1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: True


################################
### Outputs
################################
Outputs:
  S3TextLinesToSNSLambda:
    Description: "S3TextLinesToSNSLambda Lambda Function ARN"
    Value: !GetAtt S3TextLinesToSNSLambda.Arn

  S3ProcessingBucket:
    Description: "S3ProcessingBucket ARN"
    Value: !GetAtt ProcessingBucket.Arn

  FanProcesssingTable:
    Description: "FanProcessingTable ARN"
    Value: !GetAtt FanProcessingTable.Arn
  FanProcesssingTableName:
    Description: "FanProcessingTable Name"
    Value: !Select [1, !Split ['/', !GetAtt FanProcessingTable.Arn]] 

  FanProcesssingTestTableArn:
    Description: "FanProcessingTableTest ARN"
    Value: !GetAtt FanProcessingTableTest.Arn
  FanProcesssingTestTableName:
    Description: "FanProcessingTableTest Name"
    Value: !Select [1, !Split ['/', !GetAtt FanProcessingTableTest.Arn]] 

  FanProcessingPartTestTableArn:
    Description: "FanProcessingTableTest ARN"
    Value: !GetAtt FanProcessingPartTestTable.Arn
  FanProcessingPartTestTableName:
    Description: "FanProcessingTableTest Name"
    Value: !Select [1, !Split ['/', !GetAtt FanProcessingPartTestTable.Arn]] 

  FanEventsSNS:
    Description: "FanEventsSNS ARN"
    Value: !Ref FanEventsSNS
  FanEventsTestSNS:
    Description: "FanEventsTestSNS ARN"
    Value: !Ref FanEventsTestSNS

  FanStartProcessTestLambda:
    Description: "FanStartProcessTestLambda"
    Value: !Ref FanStartProcessTestLambda
